services:

  postgresdb:
    container_name: postgres_container
    image: postgres:13
    env_file:
      - .env
    ports:
    - "5432:5432"

  rabbit_mq:
    container_name: rabbit_mq
    image: rabbitmq:3.8-rc-management
    ports:
        - '5672:5672'
        - '15672:15672'

  etl_job:
    build: ./src/etl
    volumes:
    - ./src/etl:/src/etl
    env_file:
      - .env
    depends_on:
    - postgresdb
    - rabbit_mq

  api_rest:
    build: ./src/api
    volumes:
      - ./src/api:/src/api
    env_file:
      - .env
    ports:
      - 80:80
    depends_on:
      - postgresdb